apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleTemplate
metadata:
  name: replace-me
  namespace: default
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "replace-me"
  annotations:
    "operator.kyma-project.io/module-version": "0.0.4"
    "operator.kyma-project.io/module-provider": "internal"
    "operator.kyma-project.io/descriptor-schema-version": "v2"
spec:
  target: remote
  channel: stable
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: LongOperation
    metadata:
      name: longoperation-sample
    spec:
  descriptor:
    component:
      componentReferences: []
      name: kyma.project.io/module/loadtest
      provider: internal
      repositoryContexts:
        - baseUrl: europe-west3-docker.pkg.dev/sap-kyma-jellyfish-dev/loadtest-operator/unsigned
          componentNameMapping: urlPath
          type: ociRegistry
      resources:
        - access:
            digest: sha256:4d1293833dcc851452895441d123fc73aa0ea3870bd1b316c16f59644183eea9
            type: localOciBlob
          name: loadtest-operator
          relation: local
          type: helm-chart
          version: 0.0.4
      sources: []
      version: 0.0.4
    meta:
      schemaVersion: v2
    
